//cat pun data from csv, sorted by length to prevent partial replacements

const catPunData = `ampora	ampurra
approached	appurroached
approaches	appurrches
confident	confurdent
confidential	confurdential
council	pouncil
councillor	pouncellor
course	claws
depart	depurrt
departed	depurrted
departing	depurrting
ferocious	furrocious
for	fur
forget	furget
forgot	furgot
forgotten	furgotten
furious	furrious
furiously	furriously
how	meow
hypocrite	hypurrcrite
hypocrites	hypurrcrites
hypocritical	hypurrcritical
kidnap	catnap
kidnapping	catnapping
metaphorically	metafurrikitty
nap	catnap
napping	catnapping
now	meow
observation	pawbservation
observed	pawbserved
observes	pawbserves
observing	pawbserving
per	purr
percent	purrcent
percentage	purrcentage
percentages	purrcentages
perchance	purrchance
perk	purrk
perked	purrked
perks	purrks
permits	purrmits
permitted	purrmitted
permitting	purrmitting
pernickety	purrsnickety
perplex	purrplex
perplexed	purrplexed
perplexes	purrplexes
pondering	pawndering
ponders	pawnders
position	purrsition
positioning	purrsitioning
positions	purrsitions
posture	pawsture
power	pawer
powers	pawers
prefer	prefurr
prefered	prefurred
prefers	prefurrs
preposterous	prepawsterous
pretend	purrtend
pretend	purrtend
pretended	purrtended
pretended	purrtended
pretending	purrtending
pretending	purrtending
pretends	purrtends
pretends	purrtends
pretty	purrty
pursed	purrsed
risks	frisks
secret	sneakret
secrets	sneakrets
talking	stalking
telepathy	telepurrthy
transparent	transpurrent
vriska	vwiskers
transfer	transfur
transfers	transfurs
transferring	transfurring
defer	defur
defers	defurs
deferred	defurred
deferring	defurring
renew	remew
lieu	mew
Ampora	Ampurra
Approached	Appurroached
Approaches	Appurrches
Confident	Confurdent
Confidential	Confurdential
Council	Pouncil
Councillor	Pouncellor
Course	Claws
Depart	Depurrt
Departed	Depurrted
Departing	Depurrting
Ferocious	Furrocious
For	Fur
Forget	Furget
Forgot	Furgot
Forgotten	Furgotten
Furious	Furrious
Furiously	Furriously
How	Meow
Hypocrite	Hypurrcrite
Hypocrites	Hypurrcrites
Hypocritical	Hypurrcritical
Kidnap	Catnap
Kidnapping	Catnapping
Metaphorically	Metafurrikitty
Nap	Catnap
Napping	Catnapping
Now	Meow
Observation	Pawbservation
Observed	Pawbserved
Observes	Pawbserves
Observing	Pawbserving
Per	Purr
Percent	Purrcent
Percentage	Purrcentage
Percentages	Purrcentages
Perchance	Purrchance
Perk	Purrk
Perked	Purrked
Perks	Purrks
Permits	Purrmits
Permitted	Purrmitted
Permitting	Purrmitting
Pernickety	Purrsnickety
Perplex	Purrplex
Perplexed	Purrplexed
Perplexes	Purrplexes
Pondering	Pawndering
Ponders	Pawnders
Position	Purrsition
Positioning	Purrsitioning
Positions	Purrsitions
Posture	Pawsture
Power	Pawer
Powers	Pawers
Prefer	Prefurr
Prefered	Prefurred
Prefers	Prefurrs
Preposterous	Prepawsterous
Pretend	Purrtend
Pretend	Purrtend
Pretended	Purrtended
Pretended	Purrtended
Pretending	Purrtending
Pretending	Purrtending
Pretends	Purrtends
Pretends	Purrtends
Pretty	Purrty
Pursed	Purrsed
Risks	Frisks
Secret	Sneakret
Secrets	Sneakrets
Talking	Stalking
Telepathy	Telepurrthy
Transparent	Transpurrent
Vriska	Vwiskers
Transfer	Transfur
Transfers	Transfurs
Transferring	Transfurring
Defer	Defur
Defers	Defurs
Deferred	Defurred
Deferring	Defurring
Renew	Remew
Lieu	Mew
AMPORA	AMPURRA
APPROACHED	APPURROACHED
APPROACHES	APPURRCHES
CONFIDENT	CONFURDENT
CONFIDENTIAL	CONFURDENTIAL
COUNCIL	POUNCIL
COUNCILLOR	POUNCELLOR
COURSE	CLAWS
DEPART	DEPURRT
DEPARTED	DEPURRTED
DEPARTING	DEPURRTING
FEROCIOUS	FURROCIOUS
FOR	FUR
FORGET	FURGET
FORGOT	FURGOT
FORGOTTEN	FURGOTTEN
FURIOUS	FURRIOUS
FURIOUSLY	FURRIOUSLY
HOW	MEOW
HYPOCRITE	HYPURRCRITE
HYPOCRITES	HYPURRCRITES
HYPOCRITICAL	HYPURRCRITICAL
KIDNAP	CATNAP
KIDNAPPING	CATNAPPING
METAPHORICALLY	METAFURRIKITTY
NAP	CATNAP
NAPPING	CATNAPPING
NOW	MEOW
OBSERVATION	PAWBSERVATION
OBSERVED	PAWBSERVED
OBSERVES	PAWBSERVES
OBSERVING	PAWBSERVING
PER	PURR
PERCENT	PURRCENT
PERCENTAGE	PURRCENTAGE
PERCENTAGES	PURRCENTAGES
PERCHANCE	PURRCHANCE
PERK	PURRK
PERKED	PURRKED
PERKS	PURRKS
PERMITS	PURRMITS
PERMITTED	PURRMITTED
PERMITTING	PURRMITTING
PERNICKETY	PURRSNICKETY
PERPLEX	PURRPLEX
PERPLEXED	PURRPLEXED
PERPLEXES	PURRPLEXES
PONDERING	PAWNDERING
PONDERS	PAWNDERS
POSITION	PURRSITION
POSITIONING	PURRSITIONING
POSITIONS	PURRSITIONS
POSTURE	PAWSTURE
POWER	PAWER
POWERS	PAWERS
PREFER	PREFURR
PREFERED	PREFURRED
PREFERS	PREFURRS
PREPOSTEROUS	PREPAWSTEROUS
PRETEND	PURRTEND
PRETEND	PURRTEND
PRETENDED	PURRTENDED
PRETENDED	PURRTENDED
PRETENDING	PURRTENDING
PRETENDING	PURRTENDING
PRETENDS	PURRTENDS
PRETENDS	PURRTENDS
PRETTY	PURRTY
PURSED	PURRSED
RISKS	FRISKS
SECRET	SNEAKRET
SECRETS	SNEAKRETS
TALKING	STALKING
TELEPATHY	TELEPURRTHY
TRANSPARENT	TRANSPURRENT
VRISKA	VWISKERS
TRANSFER	TRANSFUR
TRANSFERS	TRANSFURS
TRANSFERRING	TRANSFURRING
DEFER	DEFUR
DEFERS	DEFURS
DEFERRED	DEFURRED
DEFERRING	DEFURRING
RENEW	REMEW
LIEU	MEW
because	beclaws
approach	apurroach
kidding	kitten
whisper	whisker
whispers	whiskers
whispering	whiskering
tale	tail
pause	paws
cause	claws
few	mew
fewer	mewer
trash	litter
louder	clowder
Because	Beclaws
Approach	Apurroach
Kidding	Kitten
Whisper	Whisker
Whispers	Whiskers
Whispering	Whiskering
Tale	Tail
Pause	Paws
Cause	Claws
Few	Mew
Fewer	Mewer
Trash	Litter
Louder	Clowder
BECAUSE	BECLAWS
APPROACH	APURROACH
KIDDING	KITTEN
WHISPER	WHISKER
WHISPERS	WHISKERS
WHISPERING	WHISKERING
TALE	TAIL
PAUSE	PAWS
CAUSE	CLAWS
FEW	MEW
FEWER	MEWER
TRASH	LITTER
LOUDER	CLOWDER
approve	apurrove
approves	apurroves
approval	apurroval
approving	apurroving
approvingly	apurrovingly
Approve	Apurrove
Approves	Apurroves
Approval	Apurroval
Approving	Apurroving
Approvingly	Apurrovingly
APPROVE	APURROVE
APPROVES	APURROVES
APPROVAL	APURROVAL
APPROVING	APURROVING
APPROVINGLY	APURROVINGLY`;

// Parse the tab-separated data into array of [word, replacement] pairs
const lines = catPunData.split('\n');
const pairs = lines.map(line => {
    const [word, replacement] = line.split('\t');
    return [word, replacement];
});
// Sort by word length (longest first) to prevent partial replacements
export const catPuns = pairs.sort((a, b) => b[0].length - a[0].length);
