//zahhak horse pun maker, added from csv, sorted by length longest first to avoid partial replacements.

const horsePunData = `fill	filly
main	mane
mains	manes
mained	maned
maim	mane
maimed	maned
maims	manes
maiming	maneing
can't	canter
rain	rein
reign	rain
raining	reining
reigning	reining
rains	reins
reigns	reins
nay	neigh
nightmare	nightmare
nightmares	nightmares
question	equestrian
questions	equestrians
have	hoove
behavioural	behoovioral
worst	horst
shudder	udder
shudders	udders
gate	gait
bolt	colt
bolts	colts
walk	hoof
walking	hoofing
instead	insteed
whine	whinny
snacking	grazing
group	herd
luck	buck
tale	tail
tales	tails
highness	harness
bundle	bale
resorting	resnorting
heard	herd
honestly	horsenestly
chopped	clopped
chop	clop
feet	hooves
foot	hoof
Fill	Filly
Main	Mane
Mains	Manes
Mained	Maned
Maim	Mane
Maimed	Maned
Maims	Manes
Maiming	Maneing
Can'T	Canter
Rain	Rein
Reign	Rain
Raining	Reining
Reigning	Reining
Rains	Reins
Reigns	Reins
Nay	Neigh
Nightmare	Nightmare
Nightmares	Nightmares
Question	Equestrian
Questions	Equestrians
Have	Hoove
Behavioural	Behoovioral
Worst	Horst
Shudder	Udder
Shudders	Udders
Gate	Gait
Bolt	Colt
Bolts	Colts
Walk	Hoof
Walking	Hoofing
Instead	Insteed
Whine	Whinny
Snacking	Grazing
Group	Herd
Luck	Buck
Tale	Tail
Tales	Tails
Highness	Harness
Bundle	Bale
Resorting	Resnorting
Heard	Herd
Honestly	Horsenestly
Chopped	Clopped
Chop	Clop
Feet	Hooves
Foot	Hoof
FILL	FILLY
MAIN	MANE
MAINS	MANES
MAINED	MANED
MAIM	MANE
MAIMED	MANED
MAIMS	MANES
MAIMING	MANEING
CAN'T	CANTER
RAIN	REIN
REIGN	RAIN
RAINING	REINING
REIGNING	REINING
RAINS	REINS
REIGNS	REINS
NAY	NEIGH
NIGHTMARE	NIGHTMARE
NIGHTMARES	NIGHTMARES
QUESTION	EQUESTRIAN
QUESTIONS	EQUESTRIANS
HAVE	HOOVE
BEHAVIOURAL	BEHOOVIORAL
WORST	HORST
SHUDDER	UDDER
SHUDDERS	UDDERS
GATE	GAIT
BOLT	COLT
BOLTS	COLTS
WALK	HOOF
WALKING	HOOFING
INSTEAD	INSTEED
WHINE	WHINNY
SNACKING	GRAZING
GROUP	HERD
LUCK	BUCK
TALE	TAIL
TALES	TAILS
HIGHNESS	HARNESS
BUNDLE	BALE
RESORTING	RESNORTING
HEARD	HERD
HONESTLY	HORSENESTLY
CHOPPED	CLOPPED
CHOP	CLOP
FEET	HOOVES
FOOT	HOOF`;

// Parse the tab-separated data into array of [word, replacement] pairs
const lines = horsePunData.split('\n');
const pairs = lines.map(line => {
    const [word, replacement] = line.split('\t');
    return [word, replacement];
});

// Sort by word length (longest first) to prevent partial replacements
export const horsePuns = pairs.sort((a, b) => b[0].length - a[0].length);
