//words ending in -ing turned to -in 

const ingData = `abiding	abidin
abusing	abusin
accusing	accusin
acing	acin
admiring	admirin
advising	advisin
aging	agin
answering	answerin
aping	apin
appearing	appearin
applying	applyin
appointing	appointin
arguing	arguin
arresting	arrestin
arriving	arrivin
asking	askin
attacking	attackin
awaking	awakin
axing	axin
bathing	bathin
bearing	bearin
beating	beatin
becoming	becomin
begging	beggin
beginning	beginnin
being	bein
believing	believin
bending	bendin
bidding	biddin
binding	bindin
blowing	blowin
boasting	boastin
breaking	breakin
breathing	breathin
breeding	breedin
bringing	bringin
building	buildin
burning	burnin
buying	buyin
calling	callin
caring	carin
carrying	carryin
catching	catchin
changing	changin
cheating	cheatin
chiding	chidin
choosing	choosin
cleaning	cleanin
clearing	clearin
climbing	climbin
clinging	clingin
closing	closin
clothing	clothin
collecting	collectin
coming	comin
comparing	comparin
completing	completin
concealing	concealin
confusing	confusin
consulting	consultin
cooking	cookin
copying	copyin
correcting	correctin
counting	countin
creeping	creepin
crossing	crossin
crying	cryin
denying	denyin
digging	diggin
doing	doin
dragging	draggin
dying	dyin
eking	ekin
eying	eyin
flowing	flowin
forgetting	forgettin
forsaking	forsakin
freezing	freezin
frying	fryin
going	goin
gripping	grippin
groaning	groanin
hating	hatin
having	havin
helping	helpin
hurting	hurtin
icing	icin
ignoring	ignorin
informing	informin
invading	invadin
joining	joinin
judging	judgin
keeping	keepin
kicking	kickin
killing	killin
kissing	kissin
kneeling	kneelin
knitting	knittin
knocking	knockin
knowing	knowin
labouring	labourin
laying	layin
leading	leadin
leaning	leanin
leaping	leapin
learning	learnin
leaving	leavin
lighting	lightin
liking	likin
listening	listenin
living	livin
loading	loadin
locking	lockin
looking	lookin
losing	losin
lying	lyin
magnifying	magnifyin
making	makin
managing	managin
marrying	marryin
meaning	meanin
measuring	measurin
meeting	meetin
melting	meltin
mending	mendin
misbehaving	misbehavin
missing	missin
mourning	mournin
moving	movin
mowing	mowin
murdering	murderin
nabbing	nabbin
napping	nappin
navigating	navigatin
needing	needin
neglecting	neglectin
negotiating	negotiatin
nibbling	nibblin
nipping	nippin
noticing	noticin
obeying	obeyin
obliging	obligin
observing	observin
obstructing	obstructin
occupying	occupyin
occurring	occurrin
offending	offendin
offering	offerin
omitting	omittin
opening	openin
opposing	opposin
packing	packin
painting	paintin
pardoning	pardonin
partaking	partakin
participating	participatin
parting	partin
penning	pennin
persuading	persuadin
pinching	pinchin
playing	playin
ploughing	ploughin
poisoning	poisonin
progressing	progressin
promising	promisin
proving	provin
putting	puttin
quaking	quakin
qualifying	qualifyin
quarrelling	quarrellin
quashing	quashin
questioning	questionin
quitting	quittin
reaching	reachin
reading	readin
rending	rendin
renting	rentin
ridding	riddin
ringing	ringin
rotting	rottin
running	runnin
saving	savin
saying	sayin
seeing	seein
seeking	seekin
selling	sellin
sending	sendin
shaking	shakin
shaping	shapin
shining	shinin
shooting	shootin
showing	showin
shrinking	shrinkin
shutting	shuttin
singing	singin
sleeping	sleepin
slitting	slittin
smelling	smellin
smiting	smitin
speaking	speakin
spilling	spillin
spinning	spinnin
spoiling	spoilin
springing	springin
standing	standin
stealing	stealin
sticking	stickin
stinging	stingin
striking	strikin
striving	strivin
suing	suin
swearing	swearin
sweeping	sweepin
swelling	swellin
swimming	swimmin
swinging	swingin
taking	takin
teaching	teachin
tearing	tearin
telling	tellin
thing	thin
thinking	thinkin
thriving	thrivin
throwing	throwin
travelling	travellin
treading	treadin
trying	tryin
tying	tyin
upholding	upholdin
using	usin
vacating	vacatin
valuing	valuin
viewing	viewin
vilifying	vilifyin
vying	vyin
wanting	wantin
washing	washin
weeping	weepin
wearing	wearin
weaving	weavin
wedding	weddin
whinging	whingin
winding	windin
winning	winnin
wishing	wishin
working	workin
wring	wrin
wringing	wringin
writing	writin
glubbing	glubbin
krilling	krillin
carping	carpin
blubbering	blubberin
trouting	troutin
eeling	eelin
crabbing	crabbin
herring	herrin
shrimping	shrimpin
Abiding	Abidin
Abusing	Abusin
Accusing	Accusin
Acing	Acin
Admiring	Admirin
Advising	Advisin
Aging	Agin
Answering	Answerin
Aping	Apin
Appearing	Appearin
Applying	Applyin
Appointing	Appointin
Arguing	Arguin
Arresting	Arrestin
Arriving	Arrivin
Asking	Askin
Attacking	Attackin
Awaking	Awakin
Axing	Axin
Bathing	Bathin
Bearing	Bearin
Beating	Beatin
Becoming	Becomin
Begging	Beggin
Beginning	Beginnin
Being	Bein
Believing	Believin
Bending	Bendin
Bidding	Biddin
Binding	Bindin
Blowing	Blowin
Boasting	Boastin
Breaking	Breakin
Breathing	Breathin
Breeding	Breedin
Bringing	Bringin
Building	Buildin
Burning	Burnin
Buying	Buyin
Calling	Callin
Caring	Carin
Carrying	Carryin
Catching	Catchin
Changing	Changin
Cheating	Cheatin
Chiding	Chidin
Choosing	Choosin
Cleaning	Cleanin
Clearing	Clearin
Climbing	Climbin
Clinging	Clingin
Closing	Closin
Clothing	Clothin
Collecting	Collectin
Coming	Comin
Comparing	Comparin
Completing	Completin
Concealing	Concealin
Confusing	Confusin
Consulting	Consultin
Cooking	Cookin
Copying	Copyin
Correcting	Correctin
Counting	Countin
Creeping	Creepin
Crossing	Crossin
Crying	Cryin
Denying	Denyin
Digging	Diggin
Doing	Doin
Dragging	Draggin
Dying	Dyin
Eking	Ekin
Eying	Eyin
Flowing	Flowin
Forgetting	Forgettin
Forsaking	Forsakin
Freezing	Freezin
Frying	Fryin
Going	Goin
Gripping	Grippin
Groaning	Groanin
Hating	Hatin
Having	Havin
Helping	Helpin
Hurting	Hurtin
Icing	Icin
Ignoring	Ignorin
Informing	Informin
Invading	Invadin
Joining	Joinin
Judging	Judgin
Keeping	Keepin
Kicking	Kickin
Killing	Killin
Kissing	Kissin
Kneeling	Kneelin
Knitting	Knittin
Knocking	Knockin
Knowing	Knowin
Labouring	Labourin
Laying	Layin
Leading	Leadin
Leaning	Leanin
Leaping	Leapin
Learning	Learnin
Leaving	Leavin
Lighting	Lightin
Liking	Likin
Listening	Listenin
Living	Livin
Loading	Loadin
Locking	Lockin
Looking	Lookin
Losing	Losin
Lying	Lyin
Magnifying	Magnifyin
Making	Makin
Managing	Managin
Marrying	Marryin
Meaning	Meanin
Measuring	Measurin
Meeting	Meetin
Melting	Meltin
Mending	Mendin
Misbehaving	Misbehavin
Missing	Missin
Mourning	Mournin
Moving	Movin
Mowing	Mowin
Murdering	Murderin
Nabbing	Nabbin
Napping	Nappin
Navigating	Navigatin
Needing	Needin
Neglecting	Neglectin
Negotiating	Negotiatin
Nibbling	Nibblin
Nipping	Nippin
Noticing	Noticin
Obeying	Obeyin
Obliging	Obligin
Observing	Observin
Obstructing	Obstructin
Occupying	Occupyin
Occurring	Occurrin
Offending	Offendin
Offering	Offerin
Omitting	Omittin
Opening	Openin
Opposing	Opposin
Packing	Packin
Painting	Paintin
Pardoning	Pardonin
Partaking	Partakin
Participating	Participatin
Parting	Partin
Penning	Pennin
Persuading	Persuadin
Pinching	Pinchin
Playing	Playin
Ploughing	Ploughin
Poisoning	Poisonin
Progressing	Progressin
Promising	Promisin
Proving	Provin
Putting	Puttin
Quaking	Quakin
Qualifying	Qualifyin
Quarrelling	Quarrellin
Quashing	Quashin
Questioning	Questionin
Quitting	Quittin
Reaching	Reachin
Reading	Readin
Rending	Rendin
Renting	Rentin
Ridding	Riddin
Ringing	Ringin
Rotting	Rottin
Running	Runnin
Saving	Savin
Saying	Sayin
Seeing	Seein
Seeking	Seekin
Selling	Sellin
Sending	Sendin
Shaking	Shakin
Shaping	Shapin
Shining	Shinin
Shooting	Shootin
Showing	Showin
Shrinking	Shrinkin
Shutting	Shuttin
Singing	Singin
Sleeping	Sleepin
Slitting	Slittin
Smelling	Smellin
Smiting	Smitin
Speaking	Speakin
Spilling	Spillin
Spinning	Spinnin
Spoiling	Spoilin
Springing	Springin
Standing	Standin
Stealing	Stealin
Sticking	Stickin
Stinging	Stingin
Striking	Strikin
Striving	Strivin
Suing	Suin
Swearing	Swearin
Sweeping	Sweepin
Swelling	Swellin
Swimming	Swimmin
Swinging	Swingin
Taking	Takin
Teaching	Teachin
Tearing	Tearin
Telling	Tellin
Thing	Thin
Thinking	Thinkin
Thriving	Thrivin
Throwing	Throwin
Travelling	Travellin
Treading	Treadin
Trying	Tryin
Tying	Tyin
Upholding	Upholdin
Using	Usin
Vacating	Vacatin
Valuing	Valuin
Viewing	Viewin
Vilifying	Vilifyin
Vying	Vyin
Wanting	Wantin
Washing	Washin
Weeping	Weepin
Wearing	Wearin
Weaving	Weavin
Wedding	Weddin
Whinging	Whingin
Winding	Windin
Winning	Winnin
Wishing	Wishin
Working	Workin
Wring	Wrin
Wringing	Wringin
Writing	Writin
Glubbing	Glubbin
Krilling	Krillin
Carping	Carpin
Blubbering	Blubberin
Trouting	Troutin
Eeling	Eelin
Crabbing	Crabbin
Herring	Herrin
Shrimping	Shrimpin
ABIDING	ABIDIN
ABUSING	ABUSIN
ACCUSING	ACCUSIN
ACING	ACIN
ADMIRING	ADMIRIN
ADVISING	ADVISIN
AGING	AGIN
ANSWERING	ANSWERIN
APING	APIN
APPEARING	APPEARIN
APPLYING	APPLYIN
APPOINTING	APPOINTIN
ARGUING	ARGUIN
ARRESTING	ARRESTIN
ARRIVING	ARRIVIN
ASKING	ASKIN
ATTACKING	ATTACKIN
AWAKING	AWAKIN
AXING	AXIN
BATHING	BATHIN
BEARING	BEARIN
BEATING	BEATIN
BECOMING	BECOMIN
BEGGING	BEGGIN
BEGINNING	BEGINNIN
BEING	BEIN
BELIEVING	BELIEVIN
BENDING	BENDIN
BIDDING	BIDDIN
BINDING	BINDIN
BLOWING	BLOWIN
BOASTING	BOASTIN
BREAKING	BREAKIN
BREATHING	BREATHIN
BREEDING	BREEDIN
BRINGING	BRINGIN
BUILDING	BUILDIN
BURNING	BURNIN
BUYING	BUYIN
CALLING	CALLIN
CARING	CARIN
CARRYING	CARRYIN
CATCHING	CATCHIN
CHANGING	CHANGIN
CHEATING	CHEATIN
CHIDING	CHIDIN
CHOOSING	CHOOSIN
CLEANING	CLEANIN
CLEARING	CLEARIN
CLIMBING	CLIMBIN
CLINGING	CLINGIN
CLOSING	CLOSIN
CLOTHING	CLOTHIN
COLLECTING	COLLECTIN
COMING	COMIN
COMPARING	COMPARIN
COMPLETING	COMPLETIN
CONCEALING	CONCEALIN
CONFUSING	CONFUSIN
CONSULTING	CONSULTIN
COOKING	COOKIN
COPYING	COPYIN
CORRECTING	CORRECTIN
COUNTING	COUNTIN
CREEPING	CREEPIN
CROSSING	CROSSIN
CRYING	CRYIN
DENYING	DENYIN
DIGGING	DIGGIN
DOING	DOIN
DRAGGING	DRAGGIN
DYING	DYIN
EKING	EKIN
EYING	EYIN
FLOWING	FLOWIN
FORGETTING	FORGETTIN
FORSAKING	FORSAKIN
FREEZING	FREEZIN
FRYING	FRYIN
GOING	GOIN
GRIPPING	GRIPPIN
GROANING	GROANIN
HATING	HATIN
HAVING	HAVIN
HELPING	HELPIN
HURTING	HURTIN
ICING	ICIN
IGNORING	IGNORIN
INFORMING	INFORMIN
INVADING	INVADIN
JOINING	JOININ
JUDGING	JUDGIN
KEEPING	KEEPIN
KICKING	KICKIN
KILLING	KILLIN
KISSING	KISSIN
KNEELING	KNEELIN
KNITTING	KNITTIN
KNOCKING	KNOCKIN
KNOWING	KNOWIN
LABOURING	LABOURIN
LAYING	LAYIN
LEADING	LEADIN
LEANING	LEANIN
LEAPING	LEAPIN
LEARNING	LEARNIN
LEAVING	LEAVIN
LIGHTING	LIGHTIN
LIKING	LIKIN
LISTENING	LISTENIN
LIVING	LIVIN
LOADING	LOADIN
LOCKING	LOCKIN
LOOKING	LOOKIN
LOSING	LOSIN
LYING	LYIN
MAGNIFYING	MAGNIFYIN
MAKING	MAKIN
MANAGING	MANAGIN
MARRYING	MARRYIN
MEANING	MEANIN
MEASURING	MEASURIN
MEETING	MEETIN
MELTING	MELTIN
MENDING	MENDIN
MISBEHAVING	MISBEHAVIN
MISSING	MISSIN
MOURNING	MOURNIN
MOVING	MOVIN
MOWING	MOWIN
MURDERING	MURDERIN
NABBING	NABBIN
NAPPING	NAPPIN
NAVIGATING	NAVIGATIN
NEEDING	NEEDIN
NEGLECTING	NEGLECTIN
NEGOTIATING	NEGOTIATIN
NIBBLING	NIBBLIN
NIPPING	NIPPIN
NOTICING	NOTICIN
OBEYING	OBEYIN
OBLIGING	OBLIGIN
OBSERVING	OBSERVIN
OBSTRUCTING	OBSTRUCTIN
OCCUPYING	OCCUPYIN
OCCURRING	OCCURRIN
OFFENDING	OFFENDIN
OFFERING	OFFERIN
OMITTING	OMITTIN
OPENING	OPENIN
OPPOSING	OPPOSIN
PACKING	PACKIN
PAINTING	PAINTIN
PARDONING	PARDONIN
PARTAKING	PARTAKIN
PARTICIPATING	PARTICIPATIN
PARTING	PARTIN
PENNING	PENNIN
PERSUADING	PERSUADIN
PINCHING	PINCHIN
PLAYING	PLAYIN
PLOUGHING	PLOUGHIN
POISONING	POISONIN
PROGRESSING	PROGRESSIN
PROMISING	PROMISIN
PROVING	PROVIN
PUTTING	PUTTIN
QUAKING	QUAKIN
QUALIFYING	QUALIFYIN
QUARRELLING	QUARRELLIN
QUASHING	QUASHIN
QUESTIONING	QUESTIONIN
QUITTING	QUITTIN
REACHING	REACHIN
READING	READIN
RENDING	RENDIN
RENTING	RENTIN
RIDDING	RIDDIN
RINGING	RINGIN
ROTTING	ROTTIN
RUNNING	RUNNIN
SAVING	SAVIN
SAYING	SAYIN
SEEING	SEEIN
SEEKING	SEEKIN
SELLING	SELLIN
SENDING	SENDIN
SHAKING	SHAKIN
SHAPING	SHAPIN
SHINING	SHININ
SHOOTING	SHOOTIN
SHOWING	SHOWIN
SHRINKING	SHRINKIN
SHUTTING	SHUTTIN
SINGING	SINGIN
SLEEPING	SLEEPIN
SLITTING	SLITTIN
SMELLING	SMELLIN
SMITING	SMITIN
SPEAKING	SPEAKIN
SPILLING	SPILLIN
SPINNING	SPINNIN
SPOILING	SPOILIN
SPRINGING	SPRINGIN
STANDING	STANDIN
STEALING	STEALIN
STICKING	STICKIN
STINGING	STINGIN
STRIKING	STRIKIN
STRIVING	STRIVIN
SUING	SUIN
SWEARING	SWEARIN
SWEEPING	SWEEPIN
SWELLING	SWELLIN
SWIMMING	SWIMMIN
SWINGING	SWINGIN
TAKING	TAKIN
TEACHING	TEACHIN
TEARING	TEARIN
TELLING	TELLIN
THING	THIN
THINKING	THINKIN
THRIVING	THRIVIN
THROWING	THROWIN
TRAVELLING	TRAVELLIN
TREADING	TREADIN
TRYING	TRYIN
TYING	TYIN
UPHOLDING	UPHOLDIN
USING	USIN
VACATING	VACATIN
VALUING	VALUIN
VIEWING	VIEWIN
VILIFYING	VILIFYIN
VYING	VYIN
WANTING	WANTIN
WASHING	WASHIN
WEEPING	WEEPIN
WEARING	WEARIN
WEAVING	WEAVIN
WEDDING	WEDDIN
WHINGING	WHINGIN
WINDING	WINDIN
WINNING	WINNIN
WISHING	WISHIN
WORKING	WORKIN
WRING	WRIN
WRINGING	WRINGIN
WRITING	WRITIN
GLUBBING	GLUBBIN
KRILLING	KRILLIN
CARPING	CARPIN
BLUBBERING	BLUBBERIN
TROUTING	TROUTIN
EELING	EELIN
CRABBING	CRABBIN
HERRING	HERRIN
SHRIMPING	SHRIMPIN
walking	walkin
talking	talkin
Walking	Walkin
Talking	Talkin
WALKING	WALKIN
TALKING	TALKIN
prancing	prancin
Prancing	Prancin
PRANCING	PRANCIN`;

//parse the tab-separated data into array of [word, replacement] pairs
const lines = ingData.split('\n');
const pairs = lines.map(line => {
    const [word, replacement] = line.split('\t');
    return [word, replacement];
});
//sort by word length (longest first) to prevent partial replacements
export const ingConverter = pairs.sort((a, b) => b[0].length - a[0].length);

