//curse filter, troll and human, including censoring not that bad words

const trollHumanCurseData = `anal	*nal
anilingus	*nilingus
anus	an*s
apeshit	*peshit
arse	*rse
arsehole	*rsehole
ass	*ss
ass-fucker	*ss-fucker
ass-hat	*ss-hat
ass-pirate	*ss-pirate
assbag	*ssbag
assbandit	*ssbandit
assbanger	*ssbanger
assbite	*ssbite
assclown	*ssclown
asscock	*sscock
asses	*sses
assface	*ssface
assfucker	*ssf***er
assfukka	*ssf***er
assgoblin	*ssgoblin
asshat	*sshat
asshead	*sshead
asshole	*ssh*le
badass	bad*ss
bastard	b*stard
bastards	b*stards
bitch	b*tch
bitcher	b*tcher
bitchers	b*tchers
bitches	b*tches
bitchin	b*tchin
bitching	b*tching
blow job	bl*w j*b
blowjob	bl*wj*b
blowjobs	bl*wj*bs
bollock	b*llock
bollocks	b*llocks
bollok	b*llok
bollox	b*llox
bondage	b*ndage
bone bulge	bone b*lge
boner	b*ner
boob	b**b
boobie	b**bie
boobs	b**bs
breasts	bre*sts
bugger	b*gger
bukkake	b*kkake
bulge	b*lge
bulge-sucker	b*lge-sucker
bulgebag	b*lgebag
bulgeface	b*lgeface
bulgehead	b*lgehead
bulgejerk	b*lgejerk
bulgejerker	b*lgejerker
bulgejockey	b*lgejockey
bulgemunch	b*lgemunch
bulgemuncher	b*lgemuncher
bulgesuck	b*lgesuck
bulgesucked	b*lgesucked
bulgesucker	b*lgesucker
bulgesucking	b*lgesucking
bulgesucks	b*lgesucks
bullshit	b*llsh*t
butt	b*tt
buttcheeks	b*ttcheeks
butthole	b*tthole
buttmunch	b*ttmunch
buttplug	b*ttplug
camslut	camsl*t
camwhore	camwh*re
circlejerk	circlej*erk
clusterfuck	clusterf**k
cock	c*ck
cock-sucker	c*ck-s*cker
cockface	c*ckface
cockhead	c*ckhead
cockjockey	c*ckjockey
cockmunch	c*ckmunch
cockmuncher	c*ckmuncher
cocks	c*cks
cockshit	c*cksh*t
cocksmith	c*cksmith
cocksuck 	c*cksuck
cocksucked 	c*cksucked
cocksucker	c*cksucker
cocksucking	c*cksucking
cocksucks 	c*cksucks
crap	cr*p
cripple	cr*pple
cripples	cr*pples
crippled	cr*ppled
cum	c*m
cumdumpster	c*mdumpster
cumguzzler	c*mguzzler
cumming	c*mming
cums	c*ms
cumshot	c*mshot
cumslut	c*msl*t
cunt	c*nt
cunts	c*nts
dammit	d*ammit
damn	d*mn
dang	d*ng
dangit	d*ngit
darn	d*rn
dick	d*ck
dickbag	d*ckbag
dickface	d*ckface
dickhead	d*ckhead
dickhole	d*ckhole
dickmilk	d*ckmilk
dicksucker	d*cksucker
dildo	d*ldo
dildos	d*ldos
dipshit	dipsh*t
dong	d*ng
dongs	d*ngs
douche	d*uche
douchebag	d*uchebag
fishfuck	f*shf**k
fishfucker	f*shf***er
frick	fr*ck
fuck	f*ck
fucked	f***ed
fucker	f***er
fuckers	f***ers
fuckhead	f***head
fuckheads	f***heads
fucking	f***ing
fucks	f***s
fuckwit	f***wit
genetic material	g*netic m*terial
globe	gl*be
globeface	gl*beface
globemunch	gl*bemunch
globemuncher	gl*bemuncher
globes	gl*bes
globesucker	gl*besucker
god-dam	god-d*m
god-damned	god-d*mned
goddamn	godd*mn
goddamned	godd*mned
goshdarn	goshd*rn
hell	h*ll
hoe	h*e
hoofbeastshit	hoofbeastsh*t
horn job	h*rn j*b
hornjob	h*rnj*b
horny	h*rny
intercourse	*ntercourse
jerk	j*rk
jerks	j*rks
jerk off	j*rk off
jerk-off 	j*rk-off
jizz	j*zz
lovemaking	l*vemaking
lust	l*st
lusting	l*sting
masochist	m*sochist
masturbate	m*sturbate
mutant	m*tant
mutants	m*tants
nipple	n*pple
nipples	n*pples
nook	n**k
nook licker	n**k l*cker
nookbag	n**kbag
nookface	n**kface
nookhead	n**khead
nookjockey	n**kjockey
nooklicker	n**kl*cker
nookmunch	n**kmunch
nookmuncher	n**kmuncher
nooks	n**ks
nude	n*de
nudity	n*dity
orgasm	*rgasm
orgasms 	*rgasms
orgy	*rgy
pailing	p*iling
penis	p*nis
piss	p*ss
pissed	p*ssed
pisses 	p*sses
poop	p**p
poopchute	p**pchute
porn	p*rn
porno	p*rno
pornography	p*rnography
pornos	p*rnos
prick	pr*ck
pricks 	pr*cks
rumble job	r*mblej*b
rumble job	r*mble j*b
rumble sphere	r*mble sphere
rumble spheres	r*mble spheres
rumblesphere	r*mblesphere
rumblespheres	r*mblespheres
sadism	s*dism
sadist	s*dist
seed flap	s**d fl*p
seedflap	s**dfl*p
seedflaps	s**dfl*ps
shame globes	shame gl*bes
shameglobes	shamegl*bes
shit	sh*t
shit-ass	sh*t-*ss
shit-bag	sh*t-bag
shit-brain	sh*t-brain
shit-breath	sh*t-breath
shit-eating	sh*t-eating
shit-face	sh*t-face
shit-faced	sh*t-faced
shit-fit	sh*t-fit
shit-head	sh*t-head
shit-heel	sh*t-heel
shit-hole	sh*t-hole
shit-house	sh*t-house
shit-load	sh*t-load
shit-sponge	sh*t-sponge
shit-stain	sh*t-stain
shitass	sh*t*ss
shitbag	sh*tbag
shitbrain	sh*tbrain
shitbreath	sh*tbreath
shiteating	sh*teating
shitface	sh*tface
shitfaced	sh*tfaced
shitfit	sh*tfit
shitfuck	sh*tfuck
shithead	sh*thead
shitheel	sh*theel
shithole	sh*thole
shithouse	sh*thouse
shitload	sh*tload
shits	sh*ts
shitsponge	sh*tsponge
shitstain	sh*tstain
shitted	sh*tted
shitter	sh*tter
shitters 	sh*tters
shittiest	sh*ttiest
shitting	sh*tting
shittings	sh*ttings
shitty	sh*tty
shitty 	sh*tty
shity	sh*ty
slut	sl*t
slutbag	sl*tbag
sluts	sl*ts
smut	sm*t
tentacle	t*ntacle
tentacles	t*ntacles
tit	t*t
tits	t*ts
titties	t*tties
titty	t*tty
turd	t*rd
twat	tw*t
twink	tw*nk
vagina	v*gina
vibrator	v*ibrator
voyeur	v*yeur
vulva	v*lva
wader	w*der
wang	w*ng
wank	w*nk
wanker	w*nker
whore	wh*re
wiggly	w*ggly
Anal	*nal
Anilingus	*nilingus
Anus	An*s
Apeshit	*peshit
Arse	*rse
Arsehole	*rsehole
Ass	*ss
Ass-Fucker	*ss-fucker
Ass-Hat	*ss-hat
Ass-Pirate	*ss-pirate
Assbag	*ssbag
Assbandit	*ssbandit
Assbanger	*ssbanger
Assbite	*ssbite
Assclown	*ssclown
Asscock	*sscock
Asses	*sses
Assface	*ssface
Assfucker	*ssf***er
Assfukka	*ssf***er
Assgoblin	*ssgoblin
Asshat	*sshat
Asshead	*sshead
Asshole	*ssh*le
Badass	Bad*ss
Bastard	B*stard
Bastards	B*stards
Bitch	B*tch
Bitcher	B*tcher
Bitchers	B*tchers
Bitches	B*tches
Bitchin	B*tchin
Bitching	B*tching
Blow Job	Bl*w j*b
Blowjob	Bl*wj*b
Blowjobs	Bl*wj*bs
Bollock	B*llock
Bollocks	B*llocks
Bollok	B*llok
Bollox	B*llox
Bondage	B*ndage
Bone Bulge	Bone b*lge
Boner	B*ner
Boob	B**b
Boobie	B**bie
Boobs	B**bs
Breasts	Bre*sts
Bugger	B*gger
Bukkake	B*kkake
Bulge	B*lge
Bulge-Sucker	B*lge-sucker
Bulgebag	B*lgebag
Bulgeface	B*lgeface
Bulgehead	B*lgehead
Bulgejerk	B*lgejerk
Bulgejerker	B*lgejerker
Bulgejockey	B*lgejockey
Bulgemunch	B*lgemunch
Bulgemuncher	B*lgemuncher
Bulgesuck	B*lgesuck
Bulgesucked	B*lgesucked
Bulgesucker	B*lgesucker
Bulgesucking	B*lgesucking
Bulgesucks	B*lgesucks
Bullshit	B*llsh*t
Butt	B*tt
Buttcheeks	B*ttcheeks
Butthole	B*tthole
Buttmunch	B*ttmunch
Buttplug	B*ttplug
Camslut	Camsl*t
Camwhore	Camwh*re
Circlejerk	Circlej*erk
Clusterfuck	Clusterf**k
Cock	C*ck
Cock-Sucker	C*ck-s*cker
Cockface	C*ckface
Cockhead	C*ckhead
Cockjockey	C*ckjockey
Cockmunch	C*ckmunch
Cockmuncher	C*ckmuncher
Cocks	C*cks
Cockshit	C*cksh*t
Cocksmith	C*cksmith
Cocksuck 	C*cksuck
Cocksucked 	C*cksucked
Cocksucker	C*cksucker
Cocksucking	C*cksucking
Cocksucks 	C*cksucks
Crap	Cr*p
Cripple	Cr*pple
Cripples	Cr*pples
Crippled	Cr*ppled
Cum	C*m
Cumdumpster	C*mdumpster
Cumguzzler	C*mguzzler
Cumming	C*mming
Cums	C*ms
Cumshot	C*mshot
Cumslut	C*msl*t
Cunt	C*nt
Cunts	C*nts
Dammit	D*ammit
Damn	D*mn
Dang	D*ng
Dangit	D*ngit
Darn	D*rn
Dick	D*ck
Dickbag	D*ckbag
Dickface	D*ckface
Dickhead	D*ckhead
Dickhole	D*ckhole
Dickmilk	D*ckmilk
Dicksucker	D*cksucker
Dildo	D*ldo
Dildos	D*ldos
Dipshit	Dipsh*t
Dong	D*ng
Dongs	D*ngs
Douche	D*uche
Douchebag	D*uchebag
Fishfuck	F*shf**k
Fishfucker	F*shf***er
Frick	Fr*ck
Fuck	F*ck
Fucked	F***ed
Fucker	F***er
Fuckers	F***ers
Fuckhead	F***head
Fuckheads	F***heads
Fucking	F***ing
Fucks	F***s
Fuckwit	F***wit
Genetic Material	G*netic m*terial
Globe	Gl*be
Globeface	Gl*beface
Globemunch	Gl*bemunch
Globemuncher	Gl*bemuncher
Globes	Gl*bes
Globesucker	Gl*besucker
God-Dam	God-d*m
God-Damned	God-d*mned
Goddamn	Godd*mn
Goddamned	Godd*mned
Goshdarn	Goshd*rn
Hell	H*ll
Hoe	H*e
Hoofbeastshit	Hoofbeastsh*t
Horn Job	H*rn j*b
Hornjob	H*rnj*b
Horny	H*rny
Intercourse	*ntercourse
Jerk	J*rk
Jerks	J*rks
Jerk Off	J*rk off
Jerk-Off 	J*rk-off
Jizz	J*zz
Lovemaking	L*vemaking
Lust	L*st
Lusting	L*sting
Masochist	M*sochist
Masturbate	M*sturbate
Mutant	M*tant
Mutants	M*tants
Nipple	N*pple
Nipples	N*pples
Nook	N**k
Nook Licker	N**k l*cker
Nookbag	N**kbag
Nookface	N**kface
Nookhead	N**khead
Nookjockey	N**kjockey
Nooklicker	N**kl*cker
Nookmunch	N**kmunch
Nookmuncher	N**kmuncher
Nooks	N**ks
Nude	N*de
Nudity	N*dity
Orgasm	*rgasm
Orgasms 	*rgasms
Orgy	*rgy
Pailing	P*iling
Penis	P*nis
Piss	P*ss
Pissed	P*ssed
Pisses 	P*sses
Poop	P**p
Poopchute	P**pchute
Porn	P*rn
Porno	P*rno
Pornography	P*rnography
Pornos	P*rnos
Prick	Pr*ck
Pricks 	Pr*cks
Rumble Job	R*mblej*b
Rumble Job	R*mble j*b
Rumble Sphere	R*mble sphere
Rumble Spheres	R*mble spheres
Rumblesphere	R*mblesphere
Rumblespheres	R*mblespheres
Sadism	S*dism
Sadist	S*dist
Seed Flap	S**d fl*p
Seedflap	S**dfl*p
Seedflaps	S**dfl*ps
Shame Globes	Shame gl*bes
Shameglobes	Shamegl*bes
Shit	Sh*t
Shit-Ass	Sh*t-*ss
Shit-Bag	Sh*t-bag
Shit-Brain	Sh*t-brain
Shit-Breath	Sh*t-breath
Shit-Eating	Sh*t-eating
Shit-Face	Sh*t-face
Shit-Faced	Sh*t-faced
Shit-Fit	Sh*t-fit
Shit-Head	Sh*t-head
Shit-Heel	Sh*t-heel
Shit-Hole	Sh*t-hole
Shit-House	Sh*t-house
Shit-Load	Sh*t-load
Shit-Sponge	Sh*t-sponge
Shit-Stain	Sh*t-stain
Shitass	Sh*t*ss
Shitbag	Sh*tbag
Shitbrain	Sh*tbrain
Shitbreath	Sh*tbreath
Shiteating	Sh*teating
Shitface	Sh*tface
Shitfaced	Sh*tfaced
Shitfit	Sh*tfit
Shitfuck	Sh*tfuck
Shithead	Sh*thead
Shitheel	Sh*theel
Shithole	Sh*thole
Shithouse	Sh*thouse
Shitload	Sh*tload
Shits	Sh*ts
Shitsponge	Sh*tsponge
Shitstain	Sh*tstain
Shitted	Sh*tted
Shitter	Sh*tter
Shitters 	Sh*tters
Shittiest	Sh*ttiest
Shitting	Sh*tting
Shittings	Sh*ttings
Shitty	Sh*tty
Shitty 	Sh*tty
Shity	Sh*ty
Slut	Sl*t
Slutbag	Sl*tbag
Sluts	Sl*ts
Smut	Sm*t
Tentacle	T*ntacle
Tentacles	T*ntacles
Tit	T*t
Tits	T*ts
Titties	T*tties
Titty	T*tty
Turd	T*rd
Twat	Tw*t
Twink	Tw*nk
Vagina	V*gina
Vibrator	V*ibrator
Voyeur	V*yeur
Vulva	V*lva
Wader	W*der
Wang	W*ng
Wank	W*nk
Wanker	W*nker
Whore	Wh*re
Wiggly	W*ggly
ANAL	*NAL
ANILINGUS	*NILINGUS
ANUS	AN*S
APESHIT	*PESHIT
ARSE	*RSE
ARSEHOLE	*RSEHOLE
ASS	*SS
ASS-FUCKER	*SS-FUCKER
ASS-HAT	*SS-HAT
ASS-PIRATE	*SS-PIRATE
ASSBAG	*SSBAG
ASSBANDIT	*SSBANDIT
ASSBANGER	*SSBANGER
ASSBITE	*SSBITE
ASSCLOWN	*SSCLOWN
ASSCOCK	*SSCOCK
ASSES	*SSES
ASSFACE	*SSFACE
ASSFUCKER	*SSF***ER
ASSFUKKA	*SSF***ER
ASSGOBLIN	*SSGOBLIN
ASSHAT	*SSHAT
ASSHEAD	*SSHEAD
ASSHOLE	*SSH*LE
BADASS	BAD*SS
BASTARD	B*STARD
BASTARDS	B*STARDS
BITCH	B*TCH
BITCHER	B*TCHER
BITCHERS	B*TCHERS
BITCHES	B*TCHES
BITCHIN	B*TCHIN
BITCHING	B*TCHING
BLOW JOB	BL*W J*B
BLOWJOB	BL*WJ*B
BLOWJOBS	BL*WJ*BS
BOLLOCK	B*LLOCK
BOLLOCKS	B*LLOCKS
BOLLOK	B*LLOK
BOLLOX	B*LLOX
BONDAGE	B*NDAGE
BONE BULGE	BONE B*LGE
BONER	B*NER
BOOB	B**B
BOOBIE	B**BIE
BOOBS	B**BS
BREASTS	BRE*STS
BUGGER	B*GGER
BUKKAKE	B*KKAKE
BULGE	B*LGE
BULGE-SUCKER	B*LGE-SUCKER
BULGEBAG	B*LGEBAG
BULGEFACE	B*LGEFACE
BULGEHEAD	B*LGEHEAD
BULGEJERK	B*LGEJERK
BULGEJERKER	B*LGEJERKER
BULGEJOCKEY	B*LGEJOCKEY
BULGEMUNCH	B*LGEMUNCH
BULGEMUNCHER	B*LGEMUNCHER
BULGESUCK	B*LGESUCK
BULGESUCKED	B*LGESUCKED
BULGESUCKER	B*LGESUCKER
BULGESUCKING	B*LGESUCKING
BULGESUCKS	B*LGESUCKS
BULLSHIT	B*LLSH*T
BUTT	B*TT
BUTTCHEEKS	B*TTCHEEKS
BUTTHOLE	B*TTHOLE
BUTTMUNCH	B*TTMUNCH
BUTTPLUG	B*TTPLUG
CAMSLUT	CAMSL*T
CAMWHORE	CAMWH*RE
CIRCLEJERK	CIRCLEJ*ERK
CLUSTERFUCK	CLUSTERF**K
COCK	C*CK
COCK-SUCKER	C*CK-S*CKER
COCKFACE	C*CKFACE
COCKHEAD	C*CKHEAD
COCKJOCKEY	C*CKJOCKEY
COCKMUNCH	C*CKMUNCH
COCKMUNCHER	C*CKMUNCHER
COCKS	C*CKS
COCKSHIT	C*CKSH*T
COCKSMITH	C*CKSMITH
COCKSUCK 	C*CKSUCK
COCKSUCKED 	C*CKSUCKED
COCKSUCKER	C*CKSUCKER
COCKSUCKING	C*CKSUCKING
COCKSUCKS 	C*CKSUCKS
CRAP	CR*P
CRIPPLE	CR*PPLE
CRIPPLES	CR*PPLES
CRIPPLED	CR*PPLED
CUM	C*M
CUMDUMPSTER	C*MDUMPSTER
CUMGUZZLER	C*MGUZZLER
CUMMING	C*MMING
CUMS	C*MS
CUMSHOT	C*MSHOT
CUMSLUT	C*MSL*T
CUNT	C*NT
CUNTS	C*NTS
DAMMIT	D*AMMIT
DAMN	D*MN
DANG	D*NG
DANGIT	D*NGIT
DARN	D*RN
DICK	D*CK
DICKBAG	D*CKBAG
DICKFACE	D*CKFACE
DICKHEAD	D*CKHEAD
DICKHOLE	D*CKHOLE
DICKMILK	D*CKMILK
DICKSUCKER	D*CKSUCKER
DILDO	D*LDO
DILDOS	D*LDOS
DIPSHIT	DIPSH*T
DONG	D*NG
DONGS	D*NGS
DOUCHE	D*UCHE
DOUCHEBAG	D*UCHEBAG
FISHFUCK	F*SHF**K
FISHFUCKER	F*SHF***ER
FRICK	FR*CK
FUCK	F*CK
FUCKED	F***ED
FUCKER	F***ER
FUCKERS	F***ERS
FUCKHEAD	F***HEAD
FUCKHEADS	F***HEADS
FUCKING	F***ING
FUCKS	F***S
FUCKWIT	F***WIT
GENETIC MATERIAL	G*NETIC M*TERIAL
GLOBE	GL*BE
GLOBEFACE	GL*BEFACE
GLOBEMUNCH	GL*BEMUNCH
GLOBEMUNCHER	GL*BEMUNCHER
GLOBES	GL*BES
GLOBESUCKER	GL*BESUCKER
GOD-DAM	GOD-D*M
GOD-DAMNED	GOD-D*MNED
GODDAMN	GODD*MN
GODDAMNED	GODD*MNED
GOSHDARN	GOSHD*RN
HELL	H*LL
HOE	H*E
HOOFBEASTSHIT	HOOFBEASTSH*T
HORN JOB	H*RN J*B
HORNJOB	H*RNJ*B
HORNY	H*RNY
INTERCOURSE	*NTERCOURSE
JERK	J*RK
JERKS	J*RKS
JERK OFF	J*RK OFF
JERK-OFF 	J*RK-OFF
JIZZ	J*ZZ
LOVEMAKING	L*VEMAKING
LUST	L*ST
LUSTING	L*STING
MASOCHIST	M*SOCHIST
MASTURBATE	M*STURBATE
MUTANT	M*TANT
MUTANTS	M*TANTS
NIPPLE	N*PPLE
NIPPLES	N*PPLES
NOOK	N**K
NOOK LICKER	N**K L*CKER
NOOKBAG	N**KBAG
NOOKFACE	N**KFACE
NOOKHEAD	N**KHEAD
NOOKJOCKEY	N**KJOCKEY
NOOKLICKER	N**KL*CKER
NOOKMUNCH	N**KMUNCH
NOOKMUNCHER	N**KMUNCHER
NOOKS	N**KS
NUDE	N*DE
NUDITY	N*DITY
ORGASM	*RGASM
ORGASMS 	*RGASMS
ORGY	*RGY
PAILING	P*ILING
PENIS	P*NIS
PISS	P*SS
PISSED	P*SSED
PISSES 	P*SSES
POOP	P**P
POOPCHUTE	P**PCHUTE
PORN	P*RN
PORNO	P*RNO
PORNOGRAPHY	P*RNOGRAPHY
PORNOS	P*RNOS
PRICK	PR*CK
PRICKS 	PR*CKS
RUMBLE JOB	R*MBLEJ*B
RUMBLE JOB	R*MBLE J*B
RUMBLE SPHERE	R*MBLE SPHERE
RUMBLE SPHERES	R*MBLE SPHERES
RUMBLESPHERE	R*MBLESPHERE
RUMBLESPHERES	R*MBLESPHERES
SADISM	S*DISM
SADIST	S*DIST
SEED FLAP	S**D FL*P
SEEDFLAP	S**DFL*P
SEEDFLAPS	S**DFL*PS
SHAME GLOBES	SHAME GL*BES
SHAMEGLOBES	SHAMEGL*BES
SHIT	SH*T
SHIT-ASS	SH*T-*SS
SHIT-BAG	SH*T-BAG
SHIT-BRAIN	SH*T-BRAIN
SHIT-BREATH	SH*T-BREATH
SHIT-EATING	SH*T-EATING
SHIT-FACE	SH*T-FACE
SHIT-FACED	SH*T-FACED
SHIT-FIT	SH*T-FIT
SHIT-HEAD	SH*T-HEAD
SHIT-HEEL	SH*T-HEEL
SHIT-HOLE	SH*T-HOLE
SHIT-HOUSE	SH*T-HOUSE
SHIT-LOAD	SH*T-LOAD
SHIT-SPONGE	SH*T-SPONGE
SHIT-STAIN	SH*T-STAIN
SHITASS	SH*T*SS
SHITBAG	SH*TBAG
SHITBRAIN	SH*TBRAIN
SHITBREATH	SH*TBREATH
SHITEATING	SH*TEATING
SHITFACE	SH*TFACE
SHITFACED	SH*TFACED
SHITFIT	SH*TFIT
SHITFUCK	SH*TFUCK
SHITHEAD	SH*THEAD
SHITHEEL	SH*THEEL
SHITHOLE	SH*THOLE
SHITHOUSE	SH*THOUSE
SHITLOAD	SH*TLOAD
SHITS	SH*TS
SHITSPONGE	SH*TSPONGE
SHITSTAIN	SH*TSTAIN
SHITTED	SH*TTED
SHITTER	SH*TTER
SHITTERS 	SH*TTERS
SHITTIEST	SH*TTIEST
SHITTING	SH*TTING
SHITTINGS	SH*TTINGS
SHITTY	SH*TTY
SHITTY 	SH*TTY
SHITY	SH*TY
SLUT	SL*T
SLUTBAG	SL*TBAG
SLUTS	SL*TS
SMUT	SM*T
TENTACLE	T*NTACLE
TENTACLES	T*NTACLES
TIT	T*T
TITS	T*TS
TITTIES	T*TTIES
TITTY	T*TTY
TURD	T*RD
TWAT	TW*T
TWINK	TW*NK
VAGINA	V*GINA
VIBRATOR	V*IBRATOR
VOYEUR	V*YEUR
VULVA	V*LVA
WADER	W*DER
WANG	W*NG
WANK	W*NK
WANKER	W*NKER
WHORE	WH*RE
WIGGLY	W*GGLY`;

//parse the tab-separated data into array of [word, replacement] pairs
const lines = trollHumanCurseData.split('\n');
const pairs = lines.map(line => {
    const [word, replacement] = line.split('\t');
    return [word, replacement];
});
//sort by word length (longest first) to prevent partial replacements
export const trollHumanCurseFiltered = pairs.sort((a, b) => b[0].length - a[0].length);
